-- KOL activation: local → prod migration v1.
-- Resolves client by NAME (clientId differs per env). Idempotent:
-- INSERT WHERE NOT EXISTS (client_id + period + username).
-- Apply with: psql --single-transaction -f this.sql

INSERT INTO moteteam.kol_activation (client_id, period, status, username, ig_link, ig_followers, ig_er, tiktok_link, tiktok_followers, tiktok_er, placement, link_post, date_post, fee, product_cost, reach, impressions, likes, comments, shares, saves, notes)
SELECT (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$), $t$2026-06$t$, $t$sudah_review$t$, $t$29ditharaaa$t$, $t$https://www.instagram.com/29ditharaaa?igsh=MTJocG5iYm0xNDV5cQ%3D%3D&utm_source=qr$t$, 14900, NULL, NULL, NULL, NULL, $t$Reels & TikTok$t$, NULL, NULL, 500000, 0, 0, 0, 0, 0, 0, 0, NULL
WHERE NOT EXISTS (SELECT 1 FROM moteteam.kol_activation x WHERE x.client_id = (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$) AND x.period = $t$2026-06$t$ AND x.username = $t$29ditharaaa$t$);
INSERT INTO moteteam.kol_activation (client_id, period, status, username, ig_link, ig_followers, ig_er, tiktok_link, tiktok_followers, tiktok_er, placement, link_post, date_post, fee, product_cost, reach, impressions, likes, comments, shares, saves, notes)
SELECT (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$), $t$2026-06$t$, $t$mau_datang_review$t$, $t$agniyanzws$t$, $t$https://www.instagram.com/agniyanzws?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==$t$, 4577, NULL, NULL, NULL, NULL, $t$Reels & TikTok$t$, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, NULL
WHERE NOT EXISTS (SELECT 1 FROM moteteam.kol_activation x WHERE x.client_id = (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$) AND x.period = $t$2026-06$t$ AND x.username = $t$agniyanzws$t$);
INSERT INTO moteteam.kol_activation (client_id, period, status, username, ig_link, ig_followers, ig_er, tiktok_link, tiktok_followers, tiktok_er, placement, link_post, date_post, fee, product_cost, reach, impressions, likes, comments, shares, saves, notes)
SELECT (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$), $t$2026-06$t$, $t$sudah_review$t$, $t$amalianazwaa$t$, $t$https://www.instagram.com/amalianazwaa?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==$t$, 3370, NULL, NULL, NULL, NULL, $t$Reels & TikTok$t$, $t$https://www.instagram.com/reel/DZpa2D7hWG3/?igsh=eTZ4cTMza2oyeHRn$t$, NULL, 0, 0, 0, 0, 0, 0, 0, 0, NULL
WHERE NOT EXISTS (SELECT 1 FROM moteteam.kol_activation x WHERE x.client_id = (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$) AND x.period = $t$2026-06$t$ AND x.username = $t$amalianazwaa$t$);
INSERT INTO moteteam.kol_activation (client_id, period, status, username, ig_link, ig_followers, ig_er, tiktok_link, tiktok_followers, tiktok_er, placement, link_post, date_post, fee, product_cost, reach, impressions, likes, comments, shares, saves, notes)
SELECT (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$), $t$2026-06$t$, $t$sudah_review$t$, $t$anggitakarlinda$t$, $t$https://www.instagram.com/anggitakarlinda?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==$t$, 7491, NULL, NULL, NULL, NULL, $t$Reels & TikTok$t$, NULL, NULL, 350000, 0, 0, 0, 0, 0, 0, 0, NULL
WHERE NOT EXISTS (SELECT 1 FROM moteteam.kol_activation x WHERE x.client_id = (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$) AND x.period = $t$2026-06$t$ AND x.username = $t$anggitakarlinda$t$);
INSERT INTO moteteam.kol_activation (client_id, period, status, username, ig_link, ig_followers, ig_er, tiktok_link, tiktok_followers, tiktok_er, placement, link_post, date_post, fee, product_cost, reach, impressions, likes, comments, shares, saves, notes)
SELECT (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$), $t$2026-06$t$, $t$sudah_review$t$, $t$arisputrraa$t$, $t$https://www.instagram.com/arisputrraa?igsh=MTJsNXlzemFodnVqOQ==$t$, 13500, NULL, NULL, NULL, NULL, $t$Reels & TikTok$t$, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, NULL
WHERE NOT EXISTS (SELECT 1 FROM moteteam.kol_activation x WHERE x.client_id = (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$) AND x.period = $t$2026-06$t$ AND x.username = $t$arisputrraa$t$);
INSERT INTO moteteam.kol_activation (client_id, period, status, username, ig_link, ig_followers, ig_er, tiktok_link, tiktok_followers, tiktok_er, placement, link_post, date_post, fee, product_cost, reach, impressions, likes, comments, shares, saves, notes)
SELECT (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$), $t$2026-06$t$, $t$sudah_review$t$, $t$azkakhoirun$t$, $t$https://www.instagram.com/azkakhoirun?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==$t$, 3455, NULL, NULL, NULL, NULL, $t$Reels & TikTok$t$, $t$https://www.instagram.com/reel/DZth_o8Rcnq/?igsh=aWlnOW42aDF1dWs=$t$, NULL, 0, 0, 0, 0, 0, 0, 0, 0, NULL
WHERE NOT EXISTS (SELECT 1 FROM moteteam.kol_activation x WHERE x.client_id = (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$) AND x.period = $t$2026-06$t$ AND x.username = $t$azkakhoirun$t$);
INSERT INTO moteteam.kol_activation (client_id, period, status, username, ig_link, ig_followers, ig_er, tiktok_link, tiktok_followers, tiktok_er, placement, link_post, date_post, fee, product_cost, reach, impressions, likes, comments, shares, saves, notes)
SELECT (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$), $t$2026-06$t$, $t$sudah_review$t$, $t$biancabeladin$t$, $t$https://www.instagram.com/biancabeladin?igsh=MWhiY3lleHJ4djZjaA==$t$, 3593, NULL, NULL, NULL, NULL, $t$Reels & TikTok$t$, $t$https://www.instagram.com/reel/DZtiD8yiEca/?igsh=YXZ5MWM4bjZrOHg4$t$, NULL, 0, 0, 0, 0, 0, 0, 0, 0, NULL
WHERE NOT EXISTS (SELECT 1 FROM moteteam.kol_activation x WHERE x.client_id = (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$) AND x.period = $t$2026-06$t$ AND x.username = $t$biancabeladin$t$);
INSERT INTO moteteam.kol_activation (client_id, period, status, username, ig_link, ig_followers, ig_er, tiktok_link, tiktok_followers, tiktok_er, placement, link_post, date_post, fee, product_cost, reach, impressions, likes, comments, shares, saves, notes)
SELECT (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$), $t$2026-06$t$, $t$sudah_review$t$, $t$bingungkemanaya$t$, $t$https://www.instagram.com/bingungkemanaya?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==$t$, 1001, NULL, NULL, NULL, NULL, $t$Reels & TikTok$t$, NULL, NULL, 50000, 0, 0, 0, 0, 0, 0, 0, NULL
WHERE NOT EXISTS (SELECT 1 FROM moteteam.kol_activation x WHERE x.client_id = (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$) AND x.period = $t$2026-06$t$ AND x.username = $t$bingungkemanaya$t$);
INSERT INTO moteteam.kol_activation (client_id, period, status, username, ig_link, ig_followers, ig_er, tiktok_link, tiktok_followers, tiktok_er, placement, link_post, date_post, fee, product_cost, reach, impressions, likes, comments, shares, saves, notes)
SELECT (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$), $t$2026-06$t$, $t$sudah_review$t$, $t$cabutkemana$t$, $t$https://www.instagram.com/cabutkemana?igsh=cDViNG14NXhzY3R2$t$, 435, NULL, NULL, NULL, NULL, $t$Reels & TikTok$t$, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, NULL
WHERE NOT EXISTS (SELECT 1 FROM moteteam.kol_activation x WHERE x.client_id = (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$) AND x.period = $t$2026-06$t$ AND x.username = $t$cabutkemana$t$);
INSERT INTO moteteam.kol_activation (client_id, period, status, username, ig_link, ig_followers, ig_er, tiktok_link, tiktok_followers, tiktok_er, placement, link_post, date_post, fee, product_cost, reach, impressions, likes, comments, shares, saves, notes)
SELECT (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$), $t$2026-06$t$, $t$sudah_review$t$, $t$cicisamdjoen$t$, $t$https://www.instagram.com/cicisamdjoen?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==$t$, 11400, NULL, NULL, NULL, NULL, $t$Reels & TikTok$t$, $t$https://www.instagram.com/reel/DZuWyiZzowD/?igsh=OHkwMmVwYjZiZHRh$t$, NULL, 0, 0, 0, 0, 0, 0, 0, 0, NULL
WHERE NOT EXISTS (SELECT 1 FROM moteteam.kol_activation x WHERE x.client_id = (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$) AND x.period = $t$2026-06$t$ AND x.username = $t$cicisamdjoen$t$);
INSERT INTO moteteam.kol_activation (client_id, period, status, username, ig_link, ig_followers, ig_er, tiktok_link, tiktok_followers, tiktok_er, placement, link_post, date_post, fee, product_cost, reach, impressions, likes, comments, shares, saves, notes)
SELECT (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$), $t$2026-06$t$, $t$mau_datang_review$t$, $t$cinderelmaaa$t$, $t$https://www.instagram.com/cinderelmaaa?igsh=ejBrb2J1NWlqMGli$t$, 10700, NULL, NULL, NULL, NULL, $t$Reels & TikTok$t$, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, NULL
WHERE NOT EXISTS (SELECT 1 FROM moteteam.kol_activation x WHERE x.client_id = (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$) AND x.period = $t$2026-06$t$ AND x.username = $t$cinderelmaaa$t$);
INSERT INTO moteteam.kol_activation (client_id, period, status, username, ig_link, ig_followers, ig_er, tiktok_link, tiktok_followers, tiktok_er, placement, link_post, date_post, fee, product_cost, reach, impressions, likes, comments, shares, saves, notes)
SELECT (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$), $t$2026-06$t$, $t$sudah_review$t$, $t$cndyrx_$t$, $t$https://www.instagram.com/cndyrx_?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==$t$, 1910, NULL, NULL, NULL, NULL, $t$Reels & TikTok$t$, $t$https://www.instagram.com/reel/DZugUBYP-pu/?igsh=eXdjMzR2bDdxcDhh$t$, NULL, 0, 0, 0, 0, 0, 0, 0, 0, NULL
WHERE NOT EXISTS (SELECT 1 FROM moteteam.kol_activation x WHERE x.client_id = (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$) AND x.period = $t$2026-06$t$ AND x.username = $t$cndyrx_$t$);
INSERT INTO moteteam.kol_activation (client_id, period, status, username, ig_link, ig_followers, ig_er, tiktok_link, tiktok_followers, tiktok_er, placement, link_post, date_post, fee, product_cost, reach, impressions, likes, comments, shares, saves, notes)
SELECT (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$), $t$2026-06$t$, $t$sudah_review$t$, $t$couplehobijalan$t$, $t$https://www.instagram.com/couplehobijalan?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==$t$, 1143, NULL, NULL, NULL, NULL, $t$Reels & TikTok$t$, NULL, NULL, 150000, 0, 0, 0, 0, 0, 0, 0, NULL
WHERE NOT EXISTS (SELECT 1 FROM moteteam.kol_activation x WHERE x.client_id = (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$) AND x.period = $t$2026-06$t$ AND x.username = $t$couplehobijalan$t$);
INSERT INTO moteteam.kol_activation (client_id, period, status, username, ig_link, ig_followers, ig_er, tiktok_link, tiktok_followers, tiktok_er, placement, link_post, date_post, fee, product_cost, reach, impressions, likes, comments, shares, saves, notes)
SELECT (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$), $t$2026-06$t$, $t$sudah_review$t$, $t$elsaniaaaa_$t$, $t$https://www.instagram.com/elsaniaaa_?igsh=MWNmeDc2cXFxcHN5eg==$t$, 17600, NULL, NULL, NULL, NULL, $t$Reels & TikTok$t$, $t$https://www.instagram.com/reel/DZuNfi0vSG3/?igsh=MWl3NnJkaXBuMHlwMg==$t$, NULL, 100000, 0, 0, 0, 0, 0, 0, 0, NULL
WHERE NOT EXISTS (SELECT 1 FROM moteteam.kol_activation x WHERE x.client_id = (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$) AND x.period = $t$2026-06$t$ AND x.username = $t$elsaniaaaa_$t$);
INSERT INTO moteteam.kol_activation (client_id, period, status, username, ig_link, ig_followers, ig_er, tiktok_link, tiktok_followers, tiktok_er, placement, link_post, date_post, fee, product_cost, reach, impressions, likes, comments, shares, saves, notes)
SELECT (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$), $t$2026-06$t$, $t$mau_datang_review$t$, $t$elutfiahjl$t$, $t$https://www.instagram.com/lutfiahjl?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==$t$, 2147, NULL, NULL, NULL, NULL, $t$Reels & TikTok$t$, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, NULL
WHERE NOT EXISTS (SELECT 1 FROM moteteam.kol_activation x WHERE x.client_id = (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$) AND x.period = $t$2026-06$t$ AND x.username = $t$elutfiahjl$t$);
INSERT INTO moteteam.kol_activation (client_id, period, status, username, ig_link, ig_followers, ig_er, tiktok_link, tiktok_followers, tiktok_er, placement, link_post, date_post, fee, product_cost, reach, impressions, likes, comments, shares, saves, notes)
SELECT (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$), $t$2026-06$t$, $t$sudah_review$t$, $t$enaw.ra$t$, $t$https://www.instagram.com/enaw.ra?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==$t$, 2556, NULL, NULL, NULL, NULL, $t$Reels & TikTok$t$, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, NULL
WHERE NOT EXISTS (SELECT 1 FROM moteteam.kol_activation x WHERE x.client_id = (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$) AND x.period = $t$2026-06$t$ AND x.username = $t$enaw.ra$t$);
INSERT INTO moteteam.kol_activation (client_id, period, status, username, ig_link, ig_followers, ig_er, tiktok_link, tiktok_followers, tiktok_er, placement, link_post, date_post, fee, product_cost, reach, impressions, likes, comments, shares, saves, notes)
SELECT (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$), $t$2026-06$t$, $t$sudah_review$t$, $t$esmeraldanurul$t$, $t$https://www.instagram.com/esmeraldanurul?igsh=bmxrb3BmM3ExOXQ4$t$, 10700, NULL, NULL, NULL, NULL, $t$Reels & TikTok$t$, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, NULL
WHERE NOT EXISTS (SELECT 1 FROM moteteam.kol_activation x WHERE x.client_id = (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$) AND x.period = $t$2026-06$t$ AND x.username = $t$esmeraldanurul$t$);
INSERT INTO moteteam.kol_activation (client_id, period, status, username, ig_link, ig_followers, ig_er, tiktok_link, tiktok_followers, tiktok_er, placement, link_post, date_post, fee, product_cost, reach, impressions, likes, comments, shares, saves, notes)
SELECT (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$), $t$2026-06$t$, $t$sudah_review$t$, $t$fairyfoodies$t$, $t$https://www.instagram.com/fairyfoodies?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==$t$, 63000, NULL, NULL, NULL, NULL, $t$Reels & TikTok$t$, NULL, NULL, 250000, 0, 0, 0, 0, 0, 0, 0, NULL
WHERE NOT EXISTS (SELECT 1 FROM moteteam.kol_activation x WHERE x.client_id = (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$) AND x.period = $t$2026-06$t$ AND x.username = $t$fairyfoodies$t$);
INSERT INTO moteteam.kol_activation (client_id, period, status, username, ig_link, ig_followers, ig_er, tiktok_link, tiktok_followers, tiktok_er, placement, link_post, date_post, fee, product_cost, reach, impressions, likes, comments, shares, saves, notes)
SELECT (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$), $t$2026-06$t$, $t$sudah_review$t$, $t$firaa.xi$t$, $t$https://www.instagram.com/firaa.xi?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==$t$, 1834, NULL, NULL, NULL, NULL, $t$Reels & TikTok$t$, NULL, NULL, 100000, 0, 0, 0, 0, 0, 0, 0, NULL
WHERE NOT EXISTS (SELECT 1 FROM moteteam.kol_activation x WHERE x.client_id = (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$) AND x.period = $t$2026-06$t$ AND x.username = $t$firaa.xi$t$);
INSERT INTO moteteam.kol_activation (client_id, period, status, username, ig_link, ig_followers, ig_er, tiktok_link, tiktok_followers, tiktok_er, placement, link_post, date_post, fee, product_cost, reach, impressions, likes, comments, shares, saves, notes)
SELECT (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$), $t$2026-06$t$, $t$sudah_review$t$, $t$irmanbr$t$, $t$https://www.instagram.com/irmanbr?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==$t$, 3151, NULL, NULL, NULL, NULL, $t$Reels & TikTok$t$, $t$https://www.instagram.com/reel/DZrHT0wBi1n/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==$t$, NULL, 0, 0, 0, 0, 0, 0, 0, 0, NULL
WHERE NOT EXISTS (SELECT 1 FROM moteteam.kol_activation x WHERE x.client_id = (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$) AND x.period = $t$2026-06$t$ AND x.username = $t$irmanbr$t$);
INSERT INTO moteteam.kol_activation (client_id, period, status, username, ig_link, ig_followers, ig_er, tiktok_link, tiktok_followers, tiktok_er, placement, link_post, date_post, fee, product_cost, reach, impressions, likes, comments, shares, saves, notes)
SELECT (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$), $t$2026-06$t$, $t$mau_datang_review$t$, $t$jajanadikadik$t$, $t$https://www.instagram.com/jajanadikadik?igsh=MXU3dWxnODFrc2Y0YQ==$t$, 275, NULL, NULL, NULL, NULL, $t$Reels & TikTok$t$, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, NULL
WHERE NOT EXISTS (SELECT 1 FROM moteteam.kol_activation x WHERE x.client_id = (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$) AND x.period = $t$2026-06$t$ AND x.username = $t$jajanadikadik$t$);
INSERT INTO moteteam.kol_activation (client_id, period, status, username, ig_link, ig_followers, ig_er, tiktok_link, tiktok_followers, tiktok_er, placement, link_post, date_post, fee, product_cost, reach, impressions, likes, comments, shares, saves, notes)
SELECT (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$), $t$2026-06$t$, $t$sudah_review$t$, $t$julidwinata.a$t$, $t$https://www.instagram.com/julidwinata.a?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==$t$, 10800, NULL, NULL, NULL, NULL, $t$Reels & TikTok$t$, NULL, NULL, 100000, 0, 0, 0, 0, 0, 0, 0, NULL
WHERE NOT EXISTS (SELECT 1 FROM moteteam.kol_activation x WHERE x.client_id = (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$) AND x.period = $t$2026-06$t$ AND x.username = $t$julidwinata.a$t$);
INSERT INTO moteteam.kol_activation (client_id, period, status, username, ig_link, ig_followers, ig_er, tiktok_link, tiktok_followers, tiktok_er, placement, link_post, date_post, fee, product_cost, reach, impressions, likes, comments, shares, saves, notes)
SELECT (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$), $t$2026-06$t$, $t$sudah_review$t$, $t$lulublqss$t$, $t$https://www.instagram.com/lulublqss?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==$t$, 4164, NULL, NULL, NULL, NULL, $t$Reels & TikTok$t$, $t$https://www.instagram.com/reel/DZmAJLBPWnm/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==$t$, NULL, 0, 0, 0, 0, 0, 0, 0, 0, NULL
WHERE NOT EXISTS (SELECT 1 FROM moteteam.kol_activation x WHERE x.client_id = (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$) AND x.period = $t$2026-06$t$ AND x.username = $t$lulublqss$t$);
INSERT INTO moteteam.kol_activation (client_id, period, status, username, ig_link, ig_followers, ig_er, tiktok_link, tiktok_followers, tiktok_er, placement, link_post, date_post, fee, product_cost, reach, impressions, likes, comments, shares, saves, notes)
SELECT (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$), $t$2026-06$t$, $t$sudah_review$t$, $t$maharanifilen$t$, $t$https://www.instagram.com/maharanifilen?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==$t$, 5597, NULL, NULL, NULL, NULL, $t$Reels & TikTok$t$, NULL, NULL, 250000, 0, 0, 0, 0, 0, 0, 0, NULL
WHERE NOT EXISTS (SELECT 1 FROM moteteam.kol_activation x WHERE x.client_id = (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$) AND x.period = $t$2026-06$t$ AND x.username = $t$maharanifilen$t$);
INSERT INTO moteteam.kol_activation (client_id, period, status, username, ig_link, ig_followers, ig_er, tiktok_link, tiktok_followers, tiktok_er, placement, link_post, date_post, fee, product_cost, reach, impressions, likes, comments, shares, saves, notes)
SELECT (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$), $t$2026-06$t$, $t$sudah_review$t$, $t$s.briena$t$, $t$https://www.instagram.com/s.briena?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==$t$, 11600, NULL, NULL, NULL, NULL, $t$Reels & TikTok$t$, $t$https://www.instagram.com/reel/DZlyr8qIu1D/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==$t$, NULL, 450000, 0, 0, 0, 0, 0, 0, 0, NULL
WHERE NOT EXISTS (SELECT 1 FROM moteteam.kol_activation x WHERE x.client_id = (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$) AND x.period = $t$2026-06$t$ AND x.username = $t$s.briena$t$);
INSERT INTO moteteam.kol_activation (client_id, period, status, username, ig_link, ig_followers, ig_er, tiktok_link, tiktok_followers, tiktok_er, placement, link_post, date_post, fee, product_cost, reach, impressions, likes, comments, shares, saves, notes)
SELECT (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$), $t$2026-06$t$, $t$sudah_review$t$, $t$saidahnf$t$, $t$https://www.instagram.com/saidahnf?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==$t$, 2513, NULL, NULL, NULL, NULL, $t$Reels & TikTok$t$, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, NULL
WHERE NOT EXISTS (SELECT 1 FROM moteteam.kol_activation x WHERE x.client_id = (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$) AND x.period = $t$2026-06$t$ AND x.username = $t$saidahnf$t$);
INSERT INTO moteteam.kol_activation (client_id, period, status, username, ig_link, ig_followers, ig_er, tiktok_link, tiktok_followers, tiktok_er, placement, link_post, date_post, fee, product_cost, reach, impressions, likes, comments, shares, saves, notes)
SELECT (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$), $t$2026-06$t$, $t$sudah_review$t$, $t$salmaputrindr$t$, $t$https://www.instagram.com/salmaaputrindr?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==$t$, 2557, NULL, NULL, NULL, NULL, $t$Reels & TikTok$t$, $t$https://www.instagram.com/reel/DZl9VqoCeBl/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==$t$, NULL, 150000, 0, 0, 0, 0, 0, 0, 0, NULL
WHERE NOT EXISTS (SELECT 1 FROM moteteam.kol_activation x WHERE x.client_id = (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$) AND x.period = $t$2026-06$t$ AND x.username = $t$salmaputrindr$t$);
INSERT INTO moteteam.kol_activation (client_id, period, status, username, ig_link, ig_followers, ig_er, tiktok_link, tiktok_followers, tiktok_er, placement, link_post, date_post, fee, product_cost, reach, impressions, likes, comments, shares, saves, notes)
SELECT (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$), $t$2026-06$t$, $t$sudah_review$t$, $t$shabrinanurd$t$, $t$https://www.instagram.com/shabrinanurd?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==$t$, 4121, NULL, NULL, NULL, NULL, $t$Reels & TikTok$t$, NULL, NULL, 250000, 0, 0, 0, 0, 0, 0, 0, NULL
WHERE NOT EXISTS (SELECT 1 FROM moteteam.kol_activation x WHERE x.client_id = (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$) AND x.period = $t$2026-06$t$ AND x.username = $t$shabrinanurd$t$);
INSERT INTO moteteam.kol_activation (client_id, period, status, username, ig_link, ig_followers, ig_er, tiktok_link, tiktok_followers, tiktok_er, placement, link_post, date_post, fee, product_cost, reach, impressions, likes, comments, shares, saves, notes)
SELECT (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$), $t$2026-06$t$, $t$sudah_review$t$, $t$vaniafirdaus$t$, $t$https://www.instagram.com/vaniafirdaus?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==$t$, 39000, NULL, NULL, NULL, NULL, $t$Reels & TikTok$t$, NULL, NULL, 400000, 0, 0, 0, 0, 0, 0, 0, NULL
WHERE NOT EXISTS (SELECT 1 FROM moteteam.kol_activation x WHERE x.client_id = (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$) AND x.period = $t$2026-06$t$ AND x.username = $t$vaniafirdaus$t$);
INSERT INTO moteteam.kol_activation (client_id, period, status, username, ig_link, ig_followers, ig_er, tiktok_link, tiktok_followers, tiktok_er, placement, link_post, date_post, fee, product_cost, reach, impressions, likes, comments, shares, saves, notes)
SELECT (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$), $t$2026-06$t$, $t$mau_datang_review$t$, $t$yessynovitasarii$t$, $t$https://www.instagram.com/yessynovitasarii?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==$t$, 19500, NULL, NULL, NULL, NULL, $t$Reels & TikTok$t$, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, NULL
WHERE NOT EXISTS (SELECT 1 FROM moteteam.kol_activation x WHERE x.client_id = (SELECT id FROM moteteam.client WHERE name = $t$Kedai Nasi Sinar Berkah$t$) AND x.period = $t$2026-06$t$ AND x.username = $t$yessynovitasarii$t$);
INSERT INTO moteteam.kol_activation (client_id, period, status, username, ig_link, ig_followers, ig_er, tiktok_link, tiktok_followers, tiktok_er, placement, link_post, date_post, fee, product_cost, reach, impressions, likes, comments, shares, saves, notes)
SELECT (SELECT id FROM moteteam.client WHERE name = $t$Rancabango Hotel & Resort$t$), $t$2026-06$t$, $t$sudah_review$t$, $t$Yovieagustina$t$, $t$https://www.instagram.com/yovieagustina?igsh=YjQwbTVsdmo2d3Zr$t$, 254000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 550000, 0, 0, 0, 0, 0, 0, 0, $t$Just Review & Showing ( villa, hotel, bungalow ) · Visit 2026-06-11$t$
WHERE NOT EXISTS (SELECT 1 FROM moteteam.kol_activation x WHERE x.client_id = (SELECT id FROM moteteam.client WHERE name = $t$Rancabango Hotel & Resort$t$) AND x.period = $t$2026-06$t$ AND x.username = $t$Yovieagustina$t$);
INSERT INTO moteteam.kol_activation (client_id, period, status, username, ig_link, ig_followers, ig_er, tiktok_link, tiktok_followers, tiktok_er, placement, link_post, date_post, fee, product_cost, reach, impressions, likes, comments, shares, saves, notes)
SELECT (SELECT id FROM moteteam.client WHERE name = $t$Rancabango Hotel & Resort$t$), $t$2026-06$t$, $t$mau_datang_review$t$, $t$alfiwidho$t$, $t$https://www.tiktok.com/@alfiwidho?_r=1&_t=ZS-97JnXPMYLJf$t$, NULL, NULL, $t$https://www.tiktok.com/@alfiwidho?_r=1&_t=ZS-97JnXPMYLJf$t$, NULL, NULL, NULL, NULL, NULL, 450000, 0, 0, 0, 0, 0, 0, 0, $t$Just Review & Showing ( villa, hotel, bungalow ) · Visit 2026-06-20$t$
WHERE NOT EXISTS (SELECT 1 FROM moteteam.kol_activation x WHERE x.client_id = (SELECT id FROM moteteam.client WHERE name = $t$Rancabango Hotel & Resort$t$) AND x.period = $t$2026-06$t$ AND x.username = $t$alfiwidho$t$);
INSERT INTO moteteam.kol_activation (client_id, period, status, username, ig_link, ig_followers, ig_er, tiktok_link, tiktok_followers, tiktok_er, placement, link_post, date_post, fee, product_cost, reach, impressions, likes, comments, shares, saves, notes)
SELECT (SELECT id FROM moteteam.client WHERE name = $t$Rancabango Hotel & Resort$t$), $t$2026-06$t$, $t$mau_datang_review$t$, $t$astridjuwita$t$, $t$https://www.instagram.com/astridjuwitaaa?igsh=c2pjaWw3ZGowZXdx$t$, 436000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 700000, 0, 0, 0, 0, 0, 0, 0, $t$Deluxe Balcony · Visit 2026-06-18$t$
WHERE NOT EXISTS (SELECT 1 FROM moteteam.kol_activation x WHERE x.client_id = (SELECT id FROM moteteam.client WHERE name = $t$Rancabango Hotel & Resort$t$) AND x.period = $t$2026-06$t$ AND x.username = $t$astridjuwita$t$);
INSERT INTO moteteam.kol_activation (client_id, period, status, username, ig_link, ig_followers, ig_er, tiktok_link, tiktok_followers, tiktok_er, placement, link_post, date_post, fee, product_cost, reach, impressions, likes, comments, shares, saves, notes)
SELECT (SELECT id FROM moteteam.client WHERE name = $t$Rancabango Hotel & Resort$t$), $t$2026-06$t$, $t$mau_datang_review$t$, $t$buncaaa01$t$, $t$https://www.instagram.com/buncaaa01?igsh=MThzZnF4ZnNxdnh3YQ==$t$, 30700, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, $t$Deluxe Balcony · Visit 2026-06-19$t$
WHERE NOT EXISTS (SELECT 1 FROM moteteam.kol_activation x WHERE x.client_id = (SELECT id FROM moteteam.client WHERE name = $t$Rancabango Hotel & Resort$t$) AND x.period = $t$2026-06$t$ AND x.username = $t$buncaaa01$t$);
INSERT INTO moteteam.kol_activation (client_id, period, status, username, ig_link, ig_followers, ig_er, tiktok_link, tiktok_followers, tiktok_er, placement, link_post, date_post, fee, product_cost, reach, impressions, likes, comments, shares, saves, notes)
SELECT (SELECT id FROM moteteam.client WHERE name = $t$Rancabango Hotel & Resort$t$), $t$2026-06$t$, $t$mau_datang_review$t$, $t$fairyangel.real$t$, $t$https://www.instagram.com/fairyangel.real?igsh=MWNzbjZkbThxZ3RobA==$t$, 169000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 750000, 0, 0, 0, 0, 0, 0, 0, $t$Just Review & Showing ( villa, hotel, bungalow ) · Visit 2026-06-17$t$
WHERE NOT EXISTS (SELECT 1 FROM moteteam.kol_activation x WHERE x.client_id = (SELECT id FROM moteteam.client WHERE name = $t$Rancabango Hotel & Resort$t$) AND x.period = $t$2026-06$t$ AND x.username = $t$fairyangel.real$t$);
INSERT INTO moteteam.kol_activation (client_id, period, status, username, ig_link, ig_followers, ig_er, tiktok_link, tiktok_followers, tiktok_er, placement, link_post, date_post, fee, product_cost, reach, impressions, likes, comments, shares, saves, notes)
SELECT (SELECT id FROM moteteam.client WHERE name = $t$Rancabango Hotel & Resort$t$), $t$2026-06$t$, $t$sudah_review$t$, $t$ines_christy$t$, $t$https://www.instagram.com/ines_christy?igsh=MXR1cjM1aXNpZDA2ZQ==$t$, 38100, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 800000, 0, 0, 0, 0, 0, 0, 0, $t$Just Review & Showing ( villa, hotel, bungalow ) · Visit 2026-06-11$t$
WHERE NOT EXISTS (SELECT 1 FROM moteteam.kol_activation x WHERE x.client_id = (SELECT id FROM moteteam.client WHERE name = $t$Rancabango Hotel & Resort$t$) AND x.period = $t$2026-06$t$ AND x.username = $t$ines_christy$t$);
INSERT INTO moteteam.kol_activation (client_id, period, status, username, ig_link, ig_followers, ig_er, tiktok_link, tiktok_followers, tiktok_er, placement, link_post, date_post, fee, product_cost, reach, impressions, likes, comments, shares, saves, notes)
SELECT (SELECT id FROM moteteam.client WHERE name = $t$Rancabango Hotel & Resort$t$), $t$2026-06$t$, $t$mau_datang_review$t$, $t$keluargasenengmaen$t$, $t$https://www.instagram.com/keluargasenengmaen?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==$t$, 43300, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 750000, 0, 0, 0, 0, 0, 0, 0, $t$Deluxe Garden · Visit 2026-06-19$t$
WHERE NOT EXISTS (SELECT 1 FROM moteteam.kol_activation x WHERE x.client_id = (SELECT id FROM moteteam.client WHERE name = $t$Rancabango Hotel & Resort$t$) AND x.period = $t$2026-06$t$ AND x.username = $t$keluargasenengmaen$t$);
INSERT INTO moteteam.kol_activation (client_id, period, status, username, ig_link, ig_followers, ig_er, tiktok_link, tiktok_followers, tiktok_er, placement, link_post, date_post, fee, product_cost, reach, impressions, likes, comments, shares, saves, notes)
SELECT (SELECT id FROM moteteam.client WHERE name = $t$Rancabango Hotel & Resort$t$), $t$2026-06$t$, $t$mau_datang_review$t$, $t$queenhungrytraveller$t$, $t$https://www.instagram.com/queenhungrytraveller?igsh=NTZibzlhbWQxMDln$t$, 23500, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, $t$Deluxe Balcony · Visit 2026-06-20$t$
WHERE NOT EXISTS (SELECT 1 FROM moteteam.kol_activation x WHERE x.client_id = (SELECT id FROM moteteam.client WHERE name = $t$Rancabango Hotel & Resort$t$) AND x.period = $t$2026-06$t$ AND x.username = $t$queenhungrytraveller$t$);
INSERT INTO moteteam.kol_activation (client_id, period, status, username, ig_link, ig_followers, ig_er, tiktok_link, tiktok_followers, tiktok_er, placement, link_post, date_post, fee, product_cost, reach, impressions, likes, comments, shares, saves, notes)
SELECT (SELECT id FROM moteteam.client WHERE name = $t$Rancabango Hotel & Resort$t$), $t$2026-06$t$, $t$mau_datang_review$t$, $t$winsyaaa$t$, $t$https://www.instagram.com/winsyaaa?igsh=cmc4Y2V0dXhuNDY5$t$, 125000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 800000, 0, 0, 0, 0, 0, 0, 0, $t$Deluxe Garden · Visit 2026-06-23$t$
WHERE NOT EXISTS (SELECT 1 FROM moteteam.kol_activation x WHERE x.client_id = (SELECT id FROM moteteam.client WHERE name = $t$Rancabango Hotel & Resort$t$) AND x.period = $t$2026-06$t$ AND x.username = $t$winsyaaa$t$);
INSERT INTO moteteam.kol_activation (client_id, period, status, username, ig_link, ig_followers, ig_er, tiktok_link, tiktok_followers, tiktok_er, placement, link_post, date_post, fee, product_cost, reach, impressions, likes, comments, shares, saves, notes)
SELECT (SELECT id FROM moteteam.client WHERE name = $t$Restorasa$t$), $t$2026-06$t$, $t$sudah_review$t$, $t$astridjuwita$t$, $t$https://www.instagram.com/astridjuwitaaa?igsh=bWNwN3N5NjBqZGh2$t$, 436000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, $t$Sudah review, belum posting$t$
WHERE NOT EXISTS (SELECT 1 FROM moteteam.kol_activation x WHERE x.client_id = (SELECT id FROM moteteam.client WHERE name = $t$Restorasa$t$) AND x.period = $t$2026-06$t$ AND x.username = $t$astridjuwita$t$);
